[package]
edition = "2021"
name = "ndarray_test"
description = "Trying out the ndarray crate."
version = "0.1.0"
authors = ["Alex Nichol <unixpickle@gmail.com>"]

[dependencies]
ndarray = { version="0.15.6" }
ndarray-rand = { version="0.14.0" }
num-traits = { version="0.2.15" }